-- SET CONTEXT
USE WAREHOUSE MOCK_WH;
USE DATABASE MOCK_DB;
USE SCHEMA RAW;

-- CREATE TABLE CUSTOMER
CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMERID STRING,
    CUSTOMERNAME STRING,
    EMAIL STRING,
    CITY STRING,
    CUSTOMERTYPE STRING
);

-- CREATE TABLE INSURANCEPOLICY
CREATE OR REPLACE TABLE INSURANCEPOLICY_RAW (
    POLICYID STRING ,
    CUSTOMERID STRING ,
    POLICYTYPE STRING ,
    COVERAGEAMOUNT DECIMAL(15, 2) ,
    PREMIUMAMOUNT DECIMAL(10, 2) ,
    POLICYSTATUS STRING 
);

-- CREATE TABLE INSURANCECLAIM
CREATE OR REPLACE TABLE INSURANCECLAIM_RAW (
    CLAIMID STRING ,
    POLICYID STRING ,
    CLAIMAMOUNT DECIMAL(15, 2),
    CLAIMDATE DATE ,
    CLAIMSTATUS STRING ,
    APPROVEDAMOUNT DECIMAL(15, 2) 
);

-- CREATE TABLE CLAIMDOCUMENT
CREATE OR REPLACE TABLE CLAIMDOCUMENT_RAW (
    DOCUMENTID STRING ,
    CLAIMID STRING ,
    DOCUMENTTYPE STRING ,
    DOCUMENTURL STRING ,
    VERIFICATIONSTATUS STRING
);

-- CREATE TABLE FRAUDALERT
CREATE OR REPLACE TABLE FRAUDALERT_RAW
(
    RAW_DATA VARIANT
);

SHOW TABLES;

-- FILE FORMAT FOR CSV
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV 
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE
TRIM_SPACE = TRUE;

-- FILE FORMAT FOR JSON
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = JSON
STRIP_OUTER_ARRAY = TRUE;

-- CREATE STAGE FOR CSV
CREATE OR REPLACE STAGE CSV_STAGE
URL = 's3://mock18csv'
CREDENTIALS = (
    AWS_KEY_ID = 'your_aws_key'
    AWS_SECRET_KEY = 'your_secret_key'
)
FILE_FORMAT = CSV_FORMAT;


-- CREATE STAGE OR JSON
CREATE OR REPLACE STAGE JSON_STAGE
URL = 's3://mock18json'
CREDENTIALS = (
    AWS_KEY_ID = 'your_aws_key'
    AWS_SECRET_KEY = 'your_secret_key'
)
FILE_FORMAT = JSON_FORMAT;


SHOW STAGES;
LIST @MOCK_DB.RAW.CSV_STAGE;

LIST @CSV_STAGE;

-- CREATE PIPE FOR CUSTOMER
CREATE OR REPLACE PIPE CUSTOMER_PIPE 
AUTO_INGEST =TRUE
AS
COPY INTO CUSTOMER_RAW
FROM @CSV_STAGE
PATTERN = '.*customer.*[.]csv';

-- CREATE STAGE FOR INSURANCEPOLICY
CREATE OR REPLACE PIPE INSURANCEPOLICY_PIPE 
AUTO_INGEST =TRUE
AS
COPY INTO INSURANCEPOLICY_RAW
FROM @CSV_STAGE
PATTERN = '.*insurance_policy.*[.]csv';

-- CREATE PIPE FOR INSURANCECLAIM
CREATE OR REPLACE PIPE INSURANCECLAIM_PIPE 
AUTO_INGEST =TRUE
AS
COPY INTO INSURANCECLAIM_RAW
FROM @CSV_STAGE
PATTERN = '.*insurance_claim.*[.]csv';

-- CREATE PIPE FOR CLAIMDOCUMENT
CREATE OR REPLACE PIPE CLAIMDOCUMENT_PIPE 
AUTO_INGEST =TRUE
AS
COPY INTO CLAIMDOCUMENT_RAW
FROM @CSV_STAGE
PATTERN = '.*claim_document.*[.]csv';

-- CREATE PIPE FOR FRAUDALERT
CREATE OR REPLACE PIPE FRAUDALERT_PIPE 
AUTO_INGEST =TRUE
AS
COPY INTO FRAUDALERT_RAW
FROM @JSON_STAGE
PATTERN = '.*fraud_alert.*[.]json';

SHOW PIPES;
LIST @CSV_STAGE;
LIST @JSON_STAGE;

SELECT COUNT(*) FROM RAW.CUSTOMER_RAW;
SELECT COUNT(*) FROM RAW.INSURANCEPOLICY_RAW;
SELECT COUNT(*) FROM RAW.INSURANCECLAIM_RAW;
SELECT COUNT(*) FROM RAW.CLAIMDOCUMENT_RAW;
SELECT COUNT(*) FROM RAW.FRAUDALERT_RAW;

SELECT COUNT(*) FROM RAW.CUSTOMER_RAW;
SELECT COUNT(*) FROM RAW.INSURANCEPOLICY_RAW;
SELECT COUNT(*) FROM RAW.INSURANCECLAIM_RAW;
SELECT COUNT(*) FROM RAW.CLAIMDOCUMENT_RAW;
SELECT COUNT(*) FROM RAW.FRAUDALERT_RAW;
