-- SET CONTEXT
USE WAREHOUSE MOCK_WH;
USE DATABASE MOCK_DB;
USE SCHEMA RAW;

-- CREATE STREAMS FOR ALL THE 5 TABLES
CREATE OR REPLACE STREAM CUSTOMER_STREAM
ON TABLE CUSTOMER_RAW;

CREATE OR REPLACE STREAM INSURANCEPOLICY_STREAM
ON TABLE INSURANCEPOLICY_RAW;

CREATE OR REPLACE STREAM INSURANCECLAIM_STREAM
ON TABLE INSURANCECLAIM_RAW;

CREATE OR REPLACE STREAM CLAIMDOCUMENT_STREAM
ON TABLE CLAIMDOCUMENT_RAW;

CREATE OR REPLACE STREAM FRAUDALERT_STREAM
ON TABLE FRAUDALERT_RAW;

SHOW STREAMS;

SELECT COUNT(*) FROM RAW.CUSTOMER_STREAM;
SELECT COUNT(*) FROM RAW.INSURANCEPOLICY_STREAM;
SELECT COUNT(*) FROM RAW.INSURANCECLAIM_STREAM;
SELECT COUNT(*) FROM RAW.CLAIMDOCUMENT_STREAM;
SELECT COUNT(*) FROM RAW.FRAUDALERT_STREAM;

