-- SET CONTEXT
USE WAREHOUSE MOCK_WH;
USE DATABASE MOCK_DB;
USE SCHEMA CORE;

-- CREATE CORE THABLE FOR CUSTOMER
CREATE OR REPLACE TABLE CORE.CUSTOMER_DIM AS
SELECT DISTINCT
TRIM(CUSTOMERID) AS CUSTOMERID,
UPPER(CUSTOMERNAME) AS CUSTOMERNAME,
LOWER(EMAIL) AS EMAIL,
UPPER(CITY) AS CITY,
UPPER(CUSTOMERTYPE) AS CUSTOMERTYPE
FROM RAW.CUSTOMER_RAW
WHERE CUSTOMERID IS NOT NULL;


SELECT COUNT(*) FROM CORE.CUSTOMER_DIM;

--CREATE CORE TABLE FOR INSURANCEPOLICY
CREATE OR REPLACE TABLE CORE.INSURANCEPOLICY_DIM AS
SELECT
POLICYID,
CUSTOMERID,
UPPER(POLICYTYPE) AS POLICYTYPE,
COVERAGEAMOUNT,
PREMIUMAMOUNT,
UPPER(POLICYSTATUS) AS POLICYSTATUS,
CASE
    WHEN COVERAGEAMOUNT > 500000 THEN 'HIGH_COVERAGE'
    ELSE 'STANDARD_COVERAGE'
END AS COVERAGE_CATEGORY
FROM RAW.INSURANCEPOLICY_RAW
WHERE PREMIUMAMOUNT >= 0;

SELECT COUNT(*) FROM CORE.INSURANCEPOLICY_DIM;

-- CREATE CORE TABLE FOR INSURANCECLAIM
CREATE OR REPLACE TABLE CORE.INSURANCECLAIM_FACT AS
SELECT
CLAIMID,
POLICYID,
CLAIMAMOUNT,
CLAIMDATE,
UPPER(CLAIMSTATUS) AS CLAIMSTATUS,
APPROVEDAMOUNT,
CASE
    WHEN APPROVEDAMOUNT > 0 THEN 'APPROVED_PAYOUT'
    ELSE 'NO_PAYOUT'
END AS CLAIM_CATEGORY,
CASE
    WHEN CLAIMAMOUNT > 20000 THEN 'HIGH_VALUE_CLAIM'
    ELSE 'NORMAL_CLAIM'
END AS CLAIM_RISK
FROM RAW.INSURANCECLAIM_RAW
WHERE CLAIMAMOUNT >= 0;

SELECT COUNT(*) FROM CORE.INSURANCECLAIM_FACT;

-- CREATE CORE TABLE FOR CLAIMDOCUMENT
CREATE OR REPLACE TABLE CORE.CLAIMDOCUMENT_DIM AS
SELECT
DOCUMENTID,
CLAIMID,
UPPER(DOCUMENTTYPE) AS DOCUMENTTYPE,
DOCUMENTURL,
UPPER(VERIFICATIONSTATUS) AS VERIFICATIONSTATUS,
CASE
    WHEN UPPER(VERIFICATIONSTATUS)='VERIFIED'
    THEN 'VALID_DOCUMENT'
    ELSE 'REQUIRES_REVIEW'
END AS DOCUMENT_CATEGORY
FROM RAW.CLAIMDOCUMENT_RAW;

SELECT COUNT(*) FROM CORE.CLAIMDOCUMENT_DIM;

-- CREATE CORE TABLE FOR FRAUDALERT
CREATE OR REPLACE TABLE CORE.FRAUDALERT_DIM AS
SELECT
RAW_DATA:alertId::STRING AS ALERT_ID,
RAW_DATA:claimId::STRING AS CLAIM_ID,
RAW_DATA:fraudScore::NUMBER AS FRAUD_SCORE,
RAW_DATA:reason::STRING AS REASON,
UPPER(RAW_DATA:alertStatus::STRING) AS ALERT_STATUS,
CASE
    WHEN RAW_DATA:fraudScore::NUMBER >= 80
    THEN 'HIGH_RISK'
    WHEN RAW_DATA:fraudScore::NUMBER >= 50
    THEN 'MEDIUM_RISK'
    ELSE 'LOW_RISK'
END AS FRAUD_RISK_LEVEL
FROM RAW.FRAUDALERT_RAW;

SELECT COUNT(*) FROM CORE.FRAUDALERT_DIM;

SHOW TABLES;

