-- SET CONTEXT
USE WAREHOUSE MOCK_WH;
USE DATABASE MOCK_DB;
USE SCHEMA CORE;

-- CREATE TASK
CREATE OR REPLACE TASK INSURANCE_CORE_TASK
WAREHOUSE = MOCK_WH
SCHEDULE = '1 MINUTE'
AS
BEGIN
INSERT INTO CORE.CUSTOMER_DIM
SELECT
    CUSTOMERID,
    UPPER(CUSTOMERNAME),
    LOWER(EMAIL),
    UPPER(CITY),
    UPPER(CUSTOMERTYPE)

FROM RAW.CUSTOMER_STREAM
WHERE CUSTOMERID IS NOT NULL;
INSERT INTO CORE.INSURANCEPOLICY_DIM
SELECT
    POLICYID,
    CUSTOMERID,
    UPPER(POLICYTYPE),
    COVERAGEAMOUNT,
    PREMIUMAMOUNT,
    UPPER(POLICYSTATUS),

    CASE
        WHEN COVERAGEAMOUNT >= 500000
        THEN 'HIGH_COVERAGE'
        ELSE 'STANDARD_COVERAGE'
    END

FROM RAW.INSURANCEPOLICY_STREAM
WHERE PREMIUMAMOUNT >= 0;
INSERT INTO CORE.INSURANCECLAIM_FACT
SELECT
    CLAIMID,
    POLICYID,
    CLAIMAMOUNT,
    CLAIMDATE,
    UPPER(CLAIMSTATUS),
    APPROVEDAMOUNT,

    CASE
        WHEN APPROVEDAMOUNT > 0
        THEN 'APPROVED_PAYOUT'
        ELSE 'NO_PAYOUT'
    END,

    CASE
        WHEN CLAIMAMOUNT >= 20000
        THEN 'HIGH_VALUE_CLAIM'
        ELSE 'NORMAL_CLAIM'
    END

FROM RAW.INSURANCECLAIM_STREAM
WHERE CLAIMAMOUNT >= 0;
INSERT INTO CORE.CLAIMDOCUMENT_DIM
SELECT
    DOCUMENTID,
    CLAIMID,
    UPPER(DOCUMENTTYPE),
    DOCUMENTURL,
    UPPER(VERIFICATIONSTATUS),

    CASE
        WHEN UPPER(VERIFICATIONSTATUS) = 'VERIFIED'
        THEN 'VALID_DOCUMENT'
        ELSE 'REQUIRES_REVIEW'
    END

FROM RAW.CLAIMDOCUMENT_STREAM;
INSERT INTO CORE.FRAUDALERT_DIM
SELECT
    RAW_DATA:alertId::STRING,
    RAW_DATA:claimId::STRING,
    RAW_DATA:fraudScore::FLOAT,
    RAW_DATA:reason::STRING,
    UPPER(RAW_DATA:alertStatus::STRING),

    CASE
        WHEN RAW_DATA:fraudScore::FLOAT >= 80
        THEN 'HIGH_RISK'

        WHEN RAW_DATA:fraudScore::FLOAT >= 50
        THEN 'MEDIUM_RISK'

        ELSE 'LOW_RISK'
    END

FROM RAW.FRAUDALERT_STREAM;

END;

SHOW TASKS;

ALTER TASK INSURANCE_CORE_TASK RESUME; 

SELECT * FROM CORE.CUSTOMER_CORE;

SELECT * FROM CORE.INSURANCEPOLICY_CORE;

SELECT * FROM CORE.INSURANCECLAIM_CORE;

SELECT * FROM CORE.CLAIMDOCUMENT_CORE;

SELECT * FROM CORE.FRAUDALERT_CORE;


