-- SET CONTEXT
USE WAREHOUSE MOCK_WH;
USE DATABASE MOCK_DB;
USE SCHEMA MART;


CREATE OR REPLACE DYNAMIC TABLE MART.INSURANCE_ANALYTICS_DYNAMIC
TARGET_LAG = '1 minute'
WAREHOUSE = MOCK_WH
AS

SELECT

    C.CUSTOMERID,
    C.CUSTOMERNAME,
    C.EMAIL,
    C.CITY,
    C.CUSTOMERTYPE,

    P.POLICYID,
    P.POLICYTYPE,
    P.COVERAGEAMOUNT,
    P.PREMIUMAMOUNT,
    P.POLICYSTATUS,
    P.COVERAGE_CATEGORY,


    F.CLAIMID,
    F.CLAIMDATE,
    F.CLAIMAMOUNT,
    F.APPROVEDAMOUNT,
    F.CLAIMSTATUS,
    F.CLAIM_CATEGORY,
    F.CLAIM_RISK,

    D.DOCUMENTID,
    D.DOCUMENTTYPE,
    D.VERIFICATIONSTATUS,
    D.DOCUMENT_CATEGORY,

    FR.ALERT_ID,
    FR.FRAUD_SCORE,
    FR.REASON,
    FR.ALERT_STATUS,
    FR.FRAUD_RISK_LEVEL

FROM CORE.CUSTOMER_DIM C

LEFT JOIN CORE.INSURANCEPOLICY_DIM P
ON C.CUSTOMERID = P.CUSTOMERID

LEFT JOIN CORE.INSURANCECLAIM_FACT F
ON P.POLICYID = F.POLICYID

LEFT JOIN CORE.CLAIMDOCUMENT_DIM D
ON F.CLAIMID = D.CLAIMID

LEFT JOIN CORE.FRAUDALERT_DIM FR
ON F.CLAIMID = FR.CLAIM_ID;

CREATE OR REPLACE VIEW MART.INSURANCE_ANALYTICS_VIEW AS
SELECT
    C.CUSTOMERID,
    C.CUSTOMERNAME,
    C.CITY,

    P.POLICYID,
    P.POLICYTYPE,
    P.COVERAGE_CATEGORY,

    F.CLAIMID,
    F.CLAIMAMOUNT,
    F.APPROVEDAMOUNT,
    F.CLAIMSTATUS,
    F.CLAIM_CATEGORY,
    F.CLAIM_RISK,

    FR.FRAUD_SCORE,
    FR.FRAUD_RISK_LEVEL
FROM CORE.CUSTOMER_DIM C
LEFT JOIN CORE.INSURANCEPOLICY_DIM P
ON C.CUSTOMERID = P.CUSTOMERID
LEFT JOIN CORE.INSURANCECLAIM_FACT F
ON P.POLICYID = F.POLICYID
LEFT JOIN CORE.FRAUDALERT_DIM FR
ON F.CLAIMID = FR.CLAIM_ID;

SELECT COUNT(*) FROM MART.INSURANCE_ANALYTICS_VIEW;

CREATE OR REPLACE MATERIALIZED VIEW MART.INSURANCE_KPI_MV AS
SELECT
    CLAIMSTATUS,
    COUNT(*) AS TOTAL_CLAIMS,
    SUM(CLAIMAMOUNT) AS TOTAL_CLAIM_AMOUNT,
    SUM(APPROVEDAMOUNT) AS TOTAL_APPROVED_AMOUNT,
    AVG(CLAIMAMOUNT) AS AVG_CLAIM_AMOUNT
FROM CORE.INSURANCECLAIM_FACT
GROUP BY CLAIMSTATUS;

SELECT COUNT(*) FROM MART.INSURANCE_KPI_MV;