--DROP ROLE FITNESS_ANALYST;
USE DATABASE MOCK_DB;
CREATE ROLE IF NOT EXISTS MOCK_ANALYSTS;
GRANT ROLE MOCK_ANALYSTS TO USER NANDHINI30;

GRANT USAGE ON DATABASE MOCK_DB TO ROLE MOCK_ANALYSTS;
GRANT USAGE ON SCHEMA MART TO ROLE MOCK_ANALYSTS;
GRANT SELECT ON ALL TABLES IN SCHEMA MART TO ROLE MOCK_ANALYSTS;

CREATE OR REPLACE MASKING POLICY EMAIL_MASK_POLICY
AS (VAL STRING)
RETURNS STRING ->

CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN')
    THEN VAL

    ELSE '********@gmail.com'
END;

ALTER TABLE CORE.CUSTOMER_DIM
MODIFY COLUMN EMAIL
SET MASKING POLICY EMAIL_MASK_POLICY;

SELECT * FROM CORE.CUSTOMER_DIM;

USE ROLE MOCK_ANALYSTS;

SELECT * FROM CORE.CUSTOMER_DIM;